export const SET_EMPLOYEES = "SET_EMPLOYEES";

// selection
export const SELECT_ALL_EMPLOYEES = "SELECT_ALL_EMPLOYEES";
export const CLEAR_EMPLOYEE_SELECTION = 'CLEAR_EMPLOYEE_SELECTION';
export const SET_SELECTED_EMPLOYEES = "SET_SELECTED_EMPLOYEES";

// sort and filter
export const SORT_EMPLOYEES = "SORT_EMPLOYEES";
export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";
